help:
    @grep '####' Makefile | sed -e 's/####//'

cart: #### Setup cart component
   @bash components/cart.sh

catalogue: #### Setup Catalogue component
   @bash components/catalogue.sh

user: #### Setup user component
   @bash components/user.sh

shipping: #### Setup shipping component
   @bash components/shipping.sh

payment: #### Setup payment component
   @bash components/payment.sh

frontend: #### Setup frontend component
   @bash components/frontend.sh

mysql: #### Setup MySQL component
    @bash components/musql.sh

redis: #### Setup redis component
   @bash components/redis.sh

rabbitmq: #### Setup rabbitmq component
   @bash components/rabbitmq.sh

mongodb: #### Setup mongodb component
   @bash components/mongodb.sh
















